// <auto-generated />
using System;
using AudioSummarizer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AudioSummarizer.Migrations
{
    [DbContext(typeof(AudioSummarizerDbContext))]
    [Migration("20251218214048_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AudioSummarizer.Models.ActionItemModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AssignedTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("AudioId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AudioId");

                    b.ToTable("ActionItems");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AssignedTo = "Reservation department",
                            AudioId = 1L,
                            CreatedDateTime = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Make a reservation",
                            IsCompleted = false
                        },
                        new
                        {
                            Id = 2L,
                            AudioId = 1L,
                            CreatedDateTime = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Send invoice",
                            IsCompleted = false
                        },
                        new
                        {
                            Id = 3L,
                            AssignedTo = "Billings department",
                            AudioId = 2L,
                            CreatedDateTime = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "request bank details",
                            IsCompleted = true
                        });
                });

            modelBuilder.Entity("AudioSummarizer.Models.AudioModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AudioFilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Audios");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AudioFilePath = "audio file path test 1",
                            CreatedDateTime = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Audio 1",
                            Summary = "Client wants to make a booking",
                            Topic = "Booking"
                        },
                        new
                        {
                            Id = 2L,
                            AudioFilePath = "audio file path test 2",
                            CreatedDateTime = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Audio 2",
                            Summary = "Client wants refund asap",
                            Topic = "Refund"
                        });
                });

            modelBuilder.Entity("AudioSummarizer.Models.ActionItemModel", b =>
                {
                    b.HasOne("AudioSummarizer.Models.AudioModel", "Audio")
                        .WithMany()
                        .HasForeignKey("AudioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Audio");
                });
#pragma warning restore 612, 618
        }
    }
}
