// <auto-generated />
using System;
using AudioSummarizer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AudioSummarizer.Migrations
{
    [DbContext(typeof(AudioSummarizerDbContext))]
    [Migration("20251219181615_Updating Call table")]
    partial class UpdatingCalltable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AudioSummarizer.Models.ActionItemModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AssignedTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("CallId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CallId");

                    b.ToTable("ActionItems");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AssignedTo = "Reservation department",
                            CallId = 1L,
                            CreatedDateTime = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Make a reservation",
                            IsCompleted = false
                        },
                        new
                        {
                            Id = 2L,
                            CallId = 1L,
                            CreatedDateTime = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Send invoice",
                            IsCompleted = false
                        },
                        new
                        {
                            Id = 3L,
                            AssignedTo = "Billings department",
                            CallId = 2L,
                            CreatedDateTime = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "request bank details",
                            IsCompleted = true,
                            UpdatedDateTime = new DateTime(2025, 1, 2, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AudioSummarizer.Models.CallModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AudioFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AudioFilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Calls");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AudioFileName = "Audio 1",
                            AudioFilePath = "audio file path test 1",
                            Category = "Booking",
                            CreatedDateTime = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Client wants to make a booking"
                        },
                        new
                        {
                            Id = 2L,
                            AudioFileName = "Audio 2",
                            AudioFilePath = "audio file path test 2",
                            Category = "Refund",
                            CreatedDateTime = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Summary = "Client wants refund asap"
                        });
                });

            modelBuilder.Entity("AudioSummarizer.Models.ActionItemModel", b =>
                {
                    b.HasOne("AudioSummarizer.Models.CallModel", "Call")
                        .WithMany()
                        .HasForeignKey("CallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Call");
                });
#pragma warning restore 612, 618
        }
    }
}
