// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RentalCall;

#nullable disable

namespace RentalCall.Migrations
{
    [DbContext(typeof(RentalCallDbContext))]
    partial class RentalCallDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RentalCall.Models.ActionItemModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("AssignedToDepartment")
                        .HasColumnType("bit");

                    b.Property<long>("CallId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CompletedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CallId");

                    b.ToTable("ActionItems");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AssignedToDepartment = true,
                            CallId = 1L,
                            CreatedDateTime = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Make a reservation",
                            IsCompleted = false,
                            UpdatedDateTime = new DateTime(2025, 1, 2, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2L,
                            AssignedToDepartment = false,
                            CallId = 2L,
                            CreatedDateTime = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Send invoice",
                            IsCompleted = false
                        },
                        new
                        {
                            Id = 3L,
                            AssignedToDepartment = true,
                            CallId = 2L,
                            CompletedDateTime = new DateTime(2025, 1, 3, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedDateTime = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "request bank details",
                            IsCompleted = true,
                            UpdatedDateTime = new DateTime(2025, 1, 2, 12, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("RentalCall.Models.CallCategoryModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CallCategories");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDateTime = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Reservations"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDateTime = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Billings"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDateTime = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Claims"
                        },
                        new
                        {
                            Id = 4L,
                            CreatedDateTime = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Maintenance"
                        },
                        new
                        {
                            Id = 5L,
                            CreatedDateTime = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Other"
                        });
                });

            modelBuilder.Entity("RentalCall.Models.CallModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("AudioFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("CallCategoryConfidence")
                        .HasColumnType("float");

                    b.Property<long>("CallCategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasActionItemError")
                        .HasColumnType("bit");

                    b.Property<bool>("HasBeenReviewed")
                        .HasColumnType("bit");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CallCategoryId");

                    b.ToTable("Calls");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AudioFileName = "Audio 1",
                            CallCategoryConfidence = 0.69999999999999996,
                            CallCategoryId = 1L,
                            CreatedDateTime = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            HasActionItemError = false,
                            HasBeenReviewed = false,
                            Summary = "Client wants to make a booking"
                        },
                        new
                        {
                            Id = 2L,
                            AudioFileName = "Audio 2",
                            CallCategoryConfidence = 0.59999999999999998,
                            CallCategoryId = 2L,
                            CreatedDateTime = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            HasActionItemError = false,
                            HasBeenReviewed = false,
                            Summary = "Client wants their refund processed asap"
                        },
                        new
                        {
                            Id = 3L,
                            AudioFileName = "Audio 3",
                            CallCategoryConfidence = 0.0,
                            CallCategoryId = 5L,
                            CreatedDateTime = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            HasActionItemError = false,
                            HasBeenReviewed = false,
                            Summary = "unknow person asking for a company donation"
                        });
                });

            modelBuilder.Entity("RentalCall.Models.UserModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<long>("UserRoleId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserRoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDateTime = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            EmailAddress = "mpatabeyacurtis@gmail.com",
                            FirstName = "Curtis",
                            IsActive = true,
                            LastName = "Beya",
                            Password = "Curtis",
                            UserRoleId = 1L
                        });
                });

            modelBuilder.Entity("RentalCall.Models.UserRoleModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedDateTime = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedDateTime = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "DepartmentManager"
                        },
                        new
                        {
                            Id = 3L,
                            CreatedDateTime = new DateTime(2025, 1, 1, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "User"
                        });
                });

            modelBuilder.Entity("RentalCall.Models.ActionItemModel", b =>
                {
                    b.HasOne("RentalCall.Models.CallModel", "Call")
                        .WithMany()
                        .HasForeignKey("CallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Call");
                });

            modelBuilder.Entity("RentalCall.Models.CallModel", b =>
                {
                    b.HasOne("RentalCall.Models.CallCategoryModel", "Category")
                        .WithMany()
                        .HasForeignKey("CallCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("RentalCall.Models.UserModel", b =>
                {
                    b.HasOne("RentalCall.Models.UserRoleModel", "UserRole")
                        .WithMany()
                        .HasForeignKey("UserRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("UserRole");
                });
#pragma warning restore 612, 618
        }
    }
}
